- hosts: webserver
  become: true
  tasks:
    - name: Cloner le proket
      git:
        repo: 'https://github.com/AeonPSR/backpack_API'
        dest: /var/www/backpack
        version: main

    - name: Installer les dépendances
      command: npm install
      args:
        chdir: /var/www/backpack
    
    - name: Générer le build
      command: npm run build
      args:
        chdir: /var/www/backpack

    - name: Vérifier si Next.js tourne déjà
      shell: pgrep -f "npm run start"
      register: nextjs_running
      ignore_errors: yes

    - name: Arrêter Next.js s'il tourne
      shell: pkill -f "npm run start"
      when: nextjs_running.rc == 0

    - name: Lancer Next.js en mode production
      shell: nohup npm run start -- --hostname 0.0.0.0 --port 3000 > /var/www/backpack/nextjs.log 2>&1 &
      args:
        chdir: /var/www/backpack